// Data for lasers, modules, and gadgets in the Beam Analytics app
const lasers = [
    { name: "None", slots: 0, minPowerPct: 0, power: 0, optimalWin: 0, optimalCharge: 0, overcharge: 0, resistance: 0, instability: 0, shatter: 0, extraction: 0 },
    { name: "Hofstede-S1 Mining Laser (S1)", slots: 1, minPowerPct: 5, power: 2100, optimalWin: 60, optimalCharge: 0, overcharge: 0, resistance: -30, instability: 10, shatter: 0, extraction: 30 },
    { name: "Arbor MHV Mining Laser (S0)", slots: 2, minPowerPct: 0, power: 0, optimalWin: 0, optimalCharge: 0, overcharge: 0, resistance: 0, instability: -40, shatter: 0, extraction: 0 },
    { name: "S00 Hofstede (S0)", slots: 2, minPowerPct: 0, power: 0, optimalWin: 40, optimalCharge: 0, overcharge: 0, resistance: -40, instability: 30, shatter: 0, extraction: 0 },
    { name: "Impact II Mining Laser (S2)", slots: 3, minPowerPct: 30, power: 3360, optimalWin: 20, optimalCharge: 0, overcharge: 0, resistance: 10, instability: -10, shatter: 0, extraction: 40 },
    { name: "Helix II Mining Laser (S2)", slots: 3, minPowerPct: 30, power: 4080, optimalWin: -40, optimalCharge: 0, overcharge: 0, resistance: -30, instability: 0, shatter: 0, extraction: 40 },
    { name: "Lawson Mining Laser (S0)", slots: 2, minPowerPct: 0, power: 0, optimalWin: 40, optimalCharge: 0, overcharge: 0, resistance: -40, instability: 30, shatter: 0, extraction: 0 },
    { name: "Klein-S2 Mining Laser (S2)", slots: 1, minPowerPct: 20, power: 3600, optimalWin: 20, optimalCharge: 0, overcharge: 0, resistance: -45, instability: 35, shatter: 0, extraction: 40 },
    { name: "Arbor MH2 Mining Laser (S2)", slots: 2, minPowerPct: 5, power: 2400, optimalWin: 40, optimalCharge: 0, overcharge: 0, resistance: 25, instability: -35, shatter: 0, extraction: 40 },
    { name: "Pitman Mining Laser (S1)", slots: 2, minPowerPct: 20, power: 3150, optimalWin: 40, optimalCharge: 0, overcharge: 0, resistance: 25, instability: 35, shatter: 0, extraction: 40 },
    { name: "MPUV Mining Laser (S1)", slots: 1, minPowerPct: 0, power: 1850, optimalWin: 0, optimalCharge: 0, overcharge: 0, resistance: 0, instability: 0, shatter: 0, extraction: 0 },
    { name: "Impact I Mining Laser (S1)", slots: 2, minPowerPct: 20, power: 2100, optimalWin: 20, optimalCharge: 0, overcharge: 0, resistance: 10, instability: -10, shatter: 0, extraction: 30 },
    { name: "Helix I Mining Laser (S1)", slots: 2, minPowerPct: 20, power: 3150, optimalWin: -40, optimalCharge: 0, overcharge: 0, resistance: -30, instability: 0, shatter: 0, extraction: 30 },
    { name: "Arbor MH1 Mining Laser (S1)", slots: 1, minPowerPct: 5, power: 1890, optimalWin: 40, optimalCharge: 0, overcharge: 0, resistance: 25, instability: -35, shatter: 0, extraction: 30 },
    { name: "S0 Helix (S0)", slots: 2, minPowerPct: 15, power: 1, optimalWin: -40, optimalCharge: 0, overcharge: 0, resistance: 0, instability: 0, shatter: 0, extraction: 0 },
    { name: "Hofstede-S2 Mining Laser (S2)", slots: 2, minPowerPct: 10, power: 3360, optimalWin: 60, optimalCharge: 0, overcharge: 0, resistance: -30, instability: 10, shatter: 0, extraction: 40 },
    { name: "Lancet MH1 Mining Laser (S1)", slots: 1, minPowerPct: 20, power: 2520, optimalWin: -60, optimalCharge: 0, overcharge: 0, resistance: 0, instability: -10, shatter: 0, extraction: 30 },
    { name: "Lancet MH2 Mining Laser (S2)", slots: 2, minPowerPct: 30, power: 3600, optimalWin: -60, optimalCharge: 0, overcharge: 0, resistance: 0, instability: -10, shatter: 0, extraction: 40 },
    { name: "Klein-S1 Mining Laser (S1)", slots: 0, minPowerPct: 15, power: 2520, optimalWin: 20, optimalCharge: 0, overcharge: 0, resistance: -45, instability: 35, shatter: 0, extraction: 30 },
];

const modules = [
    { name: "None", power: 0, optimalWin: 0, optimalCharge: 0, overcharge: 0, resistance: 0, instability: 0, shatter: 0, extraction: 0 },
    { name: "Brandt Module (Active)", power: 35, optimalWin: 0, optimalCharge: 0, overcharge: 0, resistance: 15.5, instability: 0, shatter: -30, extraction: 0 },
    { name: "Stampede Module (Active)", power: 35, optimalWin: 0, optimalCharge: 0, overcharge: 0, resistance: 0, instability: -10, shatter: -10, extraction: 0 },
    { name: "Rieger-C3 Module (Passive)", power: 25, optimalWin: -1, optimalCharge: 0, overcharge: 0, resistance: 0, instability: 0, shatter: 0, extraction: 0 },
    { name: "Rieger-C2 Module (Passive)", power: 20, optimalWin: -3, optimalCharge: 0, overcharge: 0, resistance: 0, instability: 0, shatter: 0, extraction: 0 },
    { name: "XTR Module (Passive)", power: 0, optimalWin: 15, optimalCharge: 0, overcharge: 0, resistance: 0, instability: 0, shatter: 0, extraction: 5 },
    { name: "Rieger Module (Passive)", power: 15, optimalWin: -10, optimalCharge: 0, overcharge: 0, resistance: 0, instability: 0, shatter: 0, extraction: 0 },
    { name: "Surge Module (Active)", power: 50, optimalWin: 0, optimalCharge: 0, overcharge: 0, resistance: -15.5, instability: 10, shatter: 0, extraction: 0 },
    { name: "Torpid Module (Active)", power: 0, optimalWin: 0, optimalCharge: 0, overcharge: 0, resistance: 0, instability: 0, shatter: 40, extraction: 0 },
    { name: "Rime Module (Active)", power: -15, optimalWin: 0, optimalCharge: 0, overcharge: 0, resistance: -24.8, instability: 0, shatter: -10, extraction: 0 },
    { name: "Torrent III Module (Passive)", power: 0, optimalWin: -1, optimalCharge: 0, overcharge: 0, resistance: 0, instability: 0, shatter: 0, extraction: 0 },
    { name: "Vaux Module (Passive)", power: 0, optimalWin: 0, optimalCharge: 0, overcharge: 0, resistance: 0, instability: 0, shatter: 0, extraction: 0 },
    { name: "Optimum Module (Active)", power: -15, optimalWin: 0, optimalCharge: 0, overcharge: 0, resistance: 0, instability: -10, shatter: 0, extraction: 0 },
    { name: "Forel Module (Active)", power: 0, optimalWin: 0, optimalCharge: 0, overcharge: 0, resistance: 15.5, instability: 0, shatter: 0, extraction: 0 },
    { name: "FLTR-XL Module (Passive)", power: 0, optimalWin: 0, optimalCharge: 0, overcharge: 0, resistance: 0, instability: 0, shatter: 0, extraction: 24 },
    { name: "XTR-L Module (Passive)", power: 0, optimalWin: 22, optimalCharge: 0, overcharge: 0, resistance: 0, instability: 0, shatter: 0, extraction: 5.75 },
    { name: "Focus III Module (Passive)", power: -5, optimalWin: 40, optimalCharge: 0, overcharge: 0, resistance: 0, instability: 0, shatter: 0, extraction: 0 },
    { name: "XTR-XL Module (Passive)", power: 0, optimalWin: 25, optimalCharge: 0, overcharge: 0, resistance: 0, instability: 0, shatter: 0, extraction: 6 },
    { name: "Lifeline Module (Active)", power: 0, optimalWin: 0, optimalCharge: 0, overcharge: 0, resistance: -15.5, instability: -20, shatter: 0, extraction: 0 },
    { name: "Focus II Module (Passive)", power: -10, optimalWin: 37, optimalCharge: 0, overcharge: 0, resistance: 0, instability: 0, shatter: 0, extraction: 0 },
    { name: "Vaux-C2 Module (Passive)", power: 0, optimalWin: 0, optimalCharge: 0, overcharge: 0, resistance: 0, instability: 0, shatter: 0, extraction: 0 },
    { name: "Torrent II Module (Passive)", power: 0, optimalWin: -3, optimalCharge: 0, overcharge: 0, resistance: 0, instability: 0, shatter: 0, extraction: 0 },
    { name: "Torrent Module (Passive)", power: 0, optimalWin: -10, optimalCharge: 0, overcharge: 0, resistance: 0, instability: 0, shatter: 0, extraction: 0 },
    { name: "ROC Module (Passive)", power: 0, optimalWin: 0, optimalCharge: 0, overcharge: 0, resistance: 0, instability: 0, shatter: 0, extraction: 0 },
    { name: "FLTR-L Module (Passive)", power: 0, optimalWin: 0, optimalCharge: 0, overcharge: 0, resistance: 0, instability: 0, shatter: 0, extraction: 23 },
    { name: "Vaux-C3 Module (Passive)", power: 0, optimalWin: 0, optimalCharge: 0, overcharge: 0, resistance: 0, instability: 0, shatter: 0, extraction: 0 },
    { name: "Focus Module (Passive)", power: -15, optimalWin: 30, optimalCharge: 0, overcharge: 0, resistance: 0, instability: 0, shatter: 0, extraction: 0 },
    { name: "FLTR Module (Passive)", power: 0, optimalWin: 0, optimalCharge: 0, overcharge: 0, resistance: 0, instability: 0, shatter: 0, extraction: 20 },
];

const gadgets = [
    { name: "None", power: 0, optimalWin: 0, optimalCharge: 0, overcharge: 0, resistance: 0, instability: 0, shatter: 0, extraction: 0 },
    { name: "Waveshift", power: 0, optimalWin: 100, optimalCharge: -30, overcharge: 0, resistance: 0, instability: -35, shatter: 0, extraction: 0 },
    { name: "Stalwart", power: 0, optimalWin: -30, optimalCharge: 50, overcharge: 0, resistance: 0, instability: -35, shatter: 30, extraction: 0 },
    { name: "Sabir", power: 0, optimalWin: 50, optimalCharge: 0, overcharge: 0, resistance: -50, instability: 15, shatter: 0, extraction: 0 },
    { name: "OptiMax", power: 0, optimalWin: -30, optimalCharge: 0, overcharge: 0, resistance: -25, instability: 0, shatter: 60, extraction: 0 },
    { name: "Okunis", power: 0, optimalWin: 50, optimalCharge: 100, overcharge: 0, resistance: 0, instability: 0, shatter: -20, extraction: 0 },
    { name: "BoreMax", power: 0, optimalWin: 0, optimalCharge: 0, overcharge: 0, resistance: 10, instability: -70, shatter: 30, extraction: 0 },
];